-- create a new type called grocery
-- create a new table called shopping_list
-- table should contain 6 columns, I decide what SQL data types for the columns
-- a seed file will be provided
-- the grocery type should be an ENUM that can be one of the following: main, snack, lunch, breakfast
-- none of the 6 columns should allow null values
-- primary key column id
-- name
-- price (not a string, support 2 decimal places)
-- date_added, default now()
-- checked, boolean, default false
-- category, use grocery type for this column

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12, 2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false NOT NULL,
    category grocery NOT NULL
);